theme: jekyll-theme-cayman
title: Dear Prodigy
description: Dear Prodigy is our effort to spread the joy of playing, reading, and caring among the children. Our mission is to design beautiful books, toys, and crafts that the kids will love and cherish.
